using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using Microsoft.Extensions.DependencyInjection;
using WindowsThemeManager.Core.Models;
using WindowsThemeManager.Core.Services;
using WindowsThemeManager.ViewModels;

namespace WindowsThemeManager;

/// <summary>
/// Interaction logic for MainWindow.xaml
/// </summary>
public partial class MainWindow : System.Windows.Window, INotifyPropertyChanged
{
    private bool _isDark;

    public event PropertyChangedEventHandler? PropertyChanged;

    public MainWindow()
    {
        InitializeComponent();
        Loaded += MainWindow_Loaded;
    }

    public bool IsDark
    {
        get => _isDark;
        set
        {
            if (_isDark == value) return;
            _isDark = value;
            OnPropertyChanged();
            ApplyThemeColors();
        }
    }

    private void MainWindow_Loaded(object sender, RoutedEventArgs e)
    {
        ApplyThemeColors();
    }

    /// <summary>
    /// Sets the theme mode combobox and applies theme.
    /// Call this after the DataContext is set.
    /// </summary>
    public void SetThemeMode(AppThemeMode mode)
    {
        if (ThemeModeComboBox == null)
        {
            System.Diagnostics.Trace.WriteLine($"[{DateTime.Now:O}] [MainWindow] ThemeModeComboBox is null in SetThemeMode");
            return;
        }

        ThemeModeComboBox.SelectedIndex = mode switch
        {
            AppThemeMode.System => 0,
            AppThemeMode.Light => 1,
            AppThemeMode.Dark => 2,
            _ => 0
        };

        IsDark = WindowsThemeManager.Services.ThemeManager.GetEffectiveTheme(mode) == AppThemeMode.Dark;
    }

    /// <summary>
    /// Applies colors to all named elements in the window.
    /// </summary>
    private void ApplyThemeColors()
    {
        if (!IsInitialized) return;

        var bg = IsDark ? Color.FromRgb(0x2D, 0x2D, 0x2D) : Color.FromRgb(0xF5, 0xF5, 0xF5);
        var surface = IsDark ? Color.FromRgb(0x25, 0x25, 0x25) : Color.FromRgb(0xE8, 0xE8, 0xE8);
        var surfaceAlt = IsDark ? Color.FromRgb(0x1A, 0x1A, 0x1A) : Color.FromRgb(0x1E, 0x1E, 0x1E);
        var textPrimary = IsDark ? Color.FromRgb(0xE0, 0xE0, 0xE0) : Color.FromRgb(0x00, 0x00, 0x00);
        var textSecondary = IsDark ? Color.FromRgb(0x99, 0x99, 0x99) : Color.FromRgb(0x80, 0x80, 0x80);
        var gridSplitter = IsDark ? Color.FromRgb(0x40, 0x40, 0x40) : Color.FromRgb(0xCC, 0xCC, 0xCC);
        var loadingOverlay = IsDark ? Color.FromArgb(0x80, 0x1E, 0x1E, 0x1E) : Color.FromArgb(0x80, 0xFF, 0xFF, 0xFF);

        // Window background
        RootWindow.Background = new SolidColorBrush(bg);

        // Theme panel
        ThemePanelDock.Background = new SolidColorBrush(bg);
        ThemePanelHeaderBorder.Background = new SolidColorBrush(surface);
        ThemePanelHeaderText.Foreground = new SolidColorBrush(textPrimary);

        // Loading overlay
        LoadingBorder.Background = new SolidColorBrush(loadingOverlay);

        // Monitor area
        MonitorAreaGrid.Background = new SolidColorBrush(surfaceAlt);
        MonitorAreaHeaderText.Foreground = new SolidColorBrush(IsDark ? Color.FromRgb(0xE0, 0xE0, 0xE0) : Colors.White);
        MonitorLoadingBorder.Background = new SolidColorBrush(loadingOverlay);

        // Grid splitter
        MainGridSplitter.Background = new SolidColorBrush(gridSplitter);

        // Status bar
        StatusBarBorder.Background = new SolidColorBrush(surface);
        StatusBarBorder.BorderBrush = new SolidColorBrush(gridSplitter);

        // Update theme text
        UpdateThemeItemColors();
    }

    /// <summary>
    /// Updates colors on theme list items (generated by ItemsControl).
    /// </summary>
    private void UpdateThemeItemColors()
    {
        var textPrimary = IsDark ? new SolidColorBrush(Color.FromRgb(0xE0, 0xE0, 0xE0)) : new SolidColorBrush(Color.FromRgb(0x00, 0x00, 0x00));
        var textSecondary = IsDark ? new SolidColorBrush(Color.FromRgb(0x99, 0x99, 0x99)) : new SolidColorBrush(Color.FromRgb(0x80, 0x80, 0x80));

        if (FindThemeListBox() is ListBox lb)
        {
            foreach (var item in lb.Items)
            {
                if (lb.ItemContainerGenerator.ContainerFromItem(item) is ListBoxItem container)
                {
                    foreach (var child in GetVisualChildren<TextBlock>(container))
                    {
                        // Very basic approach: color all text blocks
                        // In practice the converters handle most of the visual difference
                    }
                }
            }
        }
    }

    private static ListBox? FindThemeListBox()
    {
        // Walk the visual tree of ThemePanelDock to find the ListBox
        return FindVisualChild<ListBox>(Application.Current.MainWindow);
    }

    private static IEnumerable<T> GetVisualChildren<T>(DependencyObject parent) where T : DependencyObject
    {
        for (int i = 0; i < VisualTreeHelper.GetChildrenCount(parent); i++)
        {
            var child = VisualTreeHelper.GetChild(parent, i);
            if (child is T t) yield return t;
            foreach (var desc in GetVisualChildren<T>(child)) yield return desc;
        }
    }

    /// <summary>
    /// Handles theme mode selection change.
    /// </summary>
    private void ThemeModeComboBox_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (ThemeModeComboBox.SelectedItem is not ComboBoxItem selectedItem)
            return;

        var mode = selectedItem.Content.ToString() switch
        {
            "System" => AppThemeMode.System,
            "Light" => AppThemeMode.Light,
            "Dark" => AppThemeMode.Dark,
            _ => AppThemeMode.System
        };

        IsDark = WindowsThemeManager.Services.ThemeManager.GetEffectiveTheme(mode) == AppThemeMode.Dark;

        // Persist the setting
        var sp = App.Services;
        if (sp != null)
        {
            var settingsService = sp.GetRequiredService<SettingsService>();
            settingsService.Settings.ThemeMode = mode;
            settingsService.SaveAsync().ConfigureAwait(false);
        }
    }

    /// <summary>
    /// Window-level PreviewMouseDown. Uses coordinate-based hit testing on the Canvas.
    /// </summary>
    private void Window_PreviewMouseDown(object sender, MouseButtonEventArgs e)
    {
        if (DataContext is not MainViewModel mainVm)
            return;

        if (mainVm.Monitors.Count == 0)
            return;

        var canvas = FindVisualChild<Canvas>(MonitorsItemsControl);
        if (canvas == null)
            return;

        var clickPoint = e.GetPosition(canvas);

        foreach (var monitor in mainVm.Monitors)
        {
            double left = monitor.CanvasLeft;
            double top = monitor.CanvasTop;
            double right = left + monitor.CanvasWidth;
            double bottom = top + monitor.CanvasHeight;

            if (clickPoint.X >= left && clickPoint.X <= right &&
                clickPoint.Y >= top && clickPoint.Y <= bottom)
            {
                if (!string.IsNullOrEmpty(monitor.WallpaperPath) && System.IO.File.Exists(monitor.WallpaperPath))
                {
                    try
                    {
                        var psi = new System.Diagnostics.ProcessStartInfo
                        {
                            FileName = monitor.WallpaperPath,
                            UseShellExecute = true
                        };
                        System.Diagnostics.Process.Start(psi);
                    }
                    catch (System.Exception ex)
                    {
                        System.Diagnostics.Debug.WriteLine($"[MainWindow] Failed to open wallpaper: {ex.Message}");
                    }
                }

                e.Handled = true;
                return;
            }
        }
    }

    private static T? FindVisualChild<T>(DependencyObject? parent) where T : DependencyObject
    {
        if (parent == null) return null;
        for (int i = 0; i < VisualTreeHelper.GetChildrenCount(parent); i++)
        {
            var child = VisualTreeHelper.GetChild(parent, i);
            if (child is T t) return t;
            var found = FindVisualChild<T>(child);
            if (found != null) return found;
        }
        return null;
    }

    private void OnPropertyChanged([CallerMemberName] string? propertyName = null)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
